services:
    - type: web
      name: n8n
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      disk:
          name: n8n-data
          mountPath: /home/node/.n8n
          sizeGB: 1
      envVars:
          - key: N8N_BASIC_AUTH_ACTIVE
            value: true
          - key: N8N_BASIC_AUTH_USER
            sync: false
          - key: N8N_BASIC_AUTH_PASSWORD
            sync: false
          - key: N8N_HOST
            value: 0.0.0.0
          - key: N8N_PORT
            value: 5678
          - key: WEBHOOK_URL
            value: https://n8n-yourname.onrender.com
